### ISSUE TITLE
IRS Data Filings API Deprecated

### ISSUE THREAD

**Issue by brandonwall** [awslabs/open-data-docs#15]
Since, "the provider of this dataset will no longer maintain this dataset", will this be removed from AWS or will the current information still be available. If so, how long will this be available for?

**Comment by pschmied** [comment]
Hi Brandon, the IRS is no longer updating the dataset, and is in process of decommissioning the copy they had been maintaining in S3. I can't give you any guarantee of how long the historic data will be available. You can read their announcement regarding their change in distributing this data at https://www.irs.gov/newsroom/irs-makes-tax-exempt-organization-search-primary-source-to-get-exempt-organization-data
