### ISSUE TITLE
AOD and RGB (Asian) dust index

### ISSUE THREAD

**Issue by MilesSowden** [awslabs/open-data-docs#17]
Just wondering if AOD and RGB dust index level 2 products will be available here
Also from [open-data-docs](https://github.com/awslabs/open-data-docs)/[docs](https://github.com/awslabs/open-data-docs/tree/main/docs)/[noaa](https://github.com/awslabs/open-data-docs/tree/main/docs/noaa)/[noaa-himawari](https://github.com/awslabs/open-data-docs/tree/main/docs/noaa/noaa-himawari)/2020July08_NOAA_Himawari.pdf

**Comment by cstner** [comment]
Hi MilesSowden:

I will work with NOAA to answer your question on rePOST: https://repost.aws/questions/QUoReuWOq6TpesR7UA6FbCvQ/question-about-aod-and-rgb-asian-dust-index

**Comment by MilesSowden** [comment]
JMA lists products here: https://www.data.jma.go.jp/mscweb/en/product/product.html 

JMA saves current low res Dust index image at https://www.data.jma.go.jp/mscweb/data/himawari/img/jpn/jpn_dst_0130.jpg (URL from https://www.data.jma.go.jp/mscweb/data/himawari/sat_img.php ).

https://www.eorc.jaxa.jp/ptree/index.html has AOD and fire locations as an image viewer

Thanks

**Comment by cstner** [comment]
Hi Miles - can you please reach out to User Services at spsd.userservices@noaa.gov for this one?
