### ISSUE TITLE
Making a Radar Application using free NEXRAD radar data

### ISSUE THREAD

**Issue by BusyBird15** [awslabs/open-data-docs#30]
I'm interested in making a radar application using free NEXRAD radar data for reflectivity, velocity, etc. images.

I am looking at [this documentation page](https://github.com/awslabs/open-data-docs/blob/main/docs/noaa/noaa-nexrad/README.md) and I have a few questions:

1. Is this going to do what I want it to? I'm trying to build an app similar to RadarScope or RadarOmega using Python and libraries such as MatPlotLib and Cartopy but I'm not sure if this is the radar data I'm looking for.

2. I found under "Accessing the Real-Time data" header the endpoint for live radar data: `/<Site>/<Volume_number>/<YYYYMMDD-HHMMSS-CHUNKNUM-CHUNKTYPE>`.  It mentions `Additional documentation on the chunks is available on the last page, B-1, of this Interface Control Document.`, but this is nowhere to be found. What is `CHUNKNUM` and `CHUNKTYPE`, and what are the available values? Also I assume "HHMMSS" would be the current time?

3. How would I go about visualizing this data? How would I parse it and display it in a MatPlotLib/Cartopy (maybe even ARM-Pyart) map?

Also, if this is not going to help with what I am trying to do, where is a data source from which I can get live NEXRAD data for my Python application?

**Comment by cstner** [comment]
I would suggest reaching out to NCAR.  Their email address is on the NEXRAD registry page: https://registry.opendata.aws/noaa-nexrad/
