### ISSUE TITLE
Errors when running create table from OpenStreetMap on AWS

### ISSUE THREAD

**Issue by Nogbit** [awslabs/open-data-docs#4]
1. Using the query from this guide https://github.com/awslabs/open-data-docs/tree/main/docs/osm-pds
2. In Athena, running that query

```
CREATE EXTERNAL TABLE planet (
  id BIGINT,
  type STRING,
  tags MAP,
  lat DECIMAL(9,7),
  lon DECIMAL(10,7),
  nds ARRAY<STRUCT>,
  members ARRAY<STRUCT>,
  changeset BIGINT,
  timestamp TIMESTAMP,
  uid BIGINT,
  user STRING,
  version BIGINT,
  visible BOOLEAN
)
STORED AS ORCFILE
LOCATION 's3://osm-pds/planet/';
```

## Errors

Your query has the following error(s):

FAILED: ParseException line 1:63 mismatched input ',' expecting < near 'MAP' in map type

**Comment by jflasher** [comment]
Hi @Nogbit, I think this may be an Athena v1 vs v2 thing. Since v2 is now the default, I have updated the docs to something that works for me with v2. If you still see an issue, please reopen.

**Comment by Nogbit** [comment]
That's fantastic, thanks for resolving this so quickly.  👍
